version: "3.9"

services:
  backend:
    build: ./backend
    container_name: tickets_backend
    ports:
      - "3001:3001"
    environment:
      DB_SERVER: 192.168.1.24
      DB_PORT: 1433
      DB_USER: sa
      DB_PASSWORD: "Admin24*52*24"
      DB_NAME: SupportTickets
      PORT: 3001
    restart: on-failure

  frontend:
    build: ./frontend
    container_name: tickets_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
